// Code shown in the guides. Kept as line arrays so backticks and ${} in the snippets need no escaping.
// All of these were run in a browser before going in. Keep them working if you edit.

export const BUILD_SCRIPT = [
  "// Turns src/index.html into one data URI. Run: node build.mjs",
  "import { mkdirSync, readFileSync, writeFileSync } from \"node:fs\";",
  "import { minify } from \"terser\";",
  "",
  "const LIMIT = 3072;",
  "const src = readFileSync(\"src/index.html\", \"utf8\");",
  "",
  "// Squeeze whitespace in shaders written as glsl`...` (terser leaves strings alone).",
  "function glsl(code) {",
  "  return code",
  "    .replace(/\\/\\/.*|\\/\\*[\\s\\S]*?\\*\\//g, \"\")",
  "    .replace(/\\s+/g, \" \")",
  "    .replace(/\\s*([-+*\\/=<>(){}\\[\\];,!&|?:])\\s*/g, \"$1\")",
  "    .trim();",
  "}",
  "",
  "let html = \"\";",
  "for (const part of src.split(/(<script>[\\s\\S]*?<\\/script>|<style>[\\s\\S]*?<\\/style>)/)) {",
  "  if (part.startsWith(\"<script>\")) {",
  "    const js = part.slice(8, -9).replace(/glsl`([^`]*)`/g, (_, s) => JSON.stringify(glsl(s)));",
  "    const { code } = await minify(js, { toplevel: true, compress: { passes: 3 } });",
  "    html += \"<script>\" + code + \"</script>\";",
  "  } else if (part.startsWith(\"<style>\")) {",
  "    html += part",
  "      .replace(/\\/\\*[\\s\\S]*?\\*\\//g, \"\")",
  "      .replace(/\\s+/g, \" \")",
  "      .replace(/\\s*([{};:,>])\\s*/g, \"$1\")",
  "      .replace(/;}/g, \"}\");",
  "  } else {",
  "    html += part.replace(/<!--[\\s\\S]*?-->/g, \"\").replace(/\\s+/g, \" \").replace(/>\\s+</g, \"><\").trim();",
  "  }",
  "}",
  "",
  "// Only these three break a data URI. Encoding anything else costs bytes for nothing.",
  "const uri = \"data:text/html,\" + html.replace(/%/g, \"%25\").replace(/#/g, \"%23\").replace(/\\n/g, \"%0A\");",
  "",
  "mkdirSync(\"dist\", { recursive: true });",
  "writeFileSync(\"dist/index.html\", html);",
  "writeFileSync(\"dist/uri.txt\", uri);",
  "",
  "const bytes = Buffer.byteLength(uri);",
  "console.log(bytes + \" / \" + LIMIT + \" bytes, \" + (bytes > LIMIT ? bytes - LIMIT + \" over\" : LIMIT - bytes + \" left\"));",
].join("\n");

export const SKELETON = [
  "<body>",
  "  <canvas id=\"c\"></canvas>",
  "  <style>",
  "    body { margin: 0; overflow: hidden; background: black; }",
  "  </style>",
  "  <script>",
  "    const ctx = c.getContext(\"2d\");",
  "",
  "    // everything the app needs to remember goes up here",
  "    let player = { x: 100, y: 100 };",
  "",
  "    function update(dt) {",
  "      // move 50 pixels per second, and wrap around at the edge",
  "      player.x = (player.x + 50 * dt) % c.width;",
  "    }",
  "",
  "    function draw(time) {",
  "      ctx.fillStyle = \"black\";",
  "      ctx.fillRect(0, 0, c.width, c.height);",
  "      ctx.fillStyle = \"tomato\";",
  "      ctx.fillRect(player.x, player.y, 20, 20);",
  "    }",
  "",
  "    onresize = () => {",
  "      c.width = innerWidth;",
  "      c.height = innerHeight;",
  "    };",
  "    onresize();",
  "",
  "    let last = 0;",
  "    function frame(now) {",
  "      update(Math.min((now - last) / 1000, 0.1));",
  "      last = now;",
  "      draw(now);",
  "      requestAnimationFrame(frame);",
  "    }",
  "    requestAnimationFrame(frame);",
  "  </script>",
  "</body>",
].join("\n");

export const WEBGL = [
  "<body>",
  "  <canvas id=\"c\"></canvas>",
  "  <style>",
  "    /* full screen */",
  "    body { margin: 0; background: #000; overflow: hidden; }",
  "    canvas { display: block; }",
  "  </style>",
  "  <script>",
  "    // marks shader text for the build script. it hands the text back unchanged",
  "    const glsl = (s) => s[0];",
  "    const gl = c.getContext(\"webgl\");",
  "",
  "    // places the big triangle. you can leave this one alone",
  "    const vertex = glsl`",
  "      attribute vec2 p;",
  "      void main() { gl_Position = vec4(p, 0, 1); }",
  "    `;",
  "",
  "    // runs once for every pixel and decides its color",
  "    const fragment = glsl`",
  "      precision mediump float;",
  "      uniform float t;",
  "      uniform vec2 r;",
  "",
  "      float scene(vec3 p) {",
  "        p.xz *= mat2(cos(t), -sin(t), sin(t), cos(t));",
  "        p.yz *= mat2(cos(t * .7), -sin(t * .7), sin(t * .7), cos(t * .7));",
  "        return length(max(abs(p) - .6, 0.)) - .1;",
  "      }",
  "",
  "      void main() {",
  "        vec2 uv = (gl_FragCoord.xy * 2. - r) / r.y;",
  "        vec3 p = vec3(0, 0, -3), dir = normalize(vec3(uv, 1.5));",
  "        float d = 1.;",
  "        for (int i = 0; i < 80; i++) {",
  "          d = scene(p);",
  "          if (d < .001) break;",
  "          p += dir * d;",
  "        }",
  "        vec3 color = vec3(0);",
  "        if (d < .001) {",
  "          vec2 e = vec2(.001, 0);",
  "          vec3 n = normalize(vec3(",
  "            scene(p + e.xyy) - scene(p - e.xyy),",
  "            scene(p + e.yxy) - scene(p - e.yxy),",
  "            scene(p + e.yyx) - scene(p - e.yyx)",
  "          ));",
  "          color = vec3(1, .75, .1) * max(dot(n, normalize(vec3(1, 1, -1))), .15);",
  "        }",
  "        gl_FragColor = vec4(color, 1);",
  "      }",
  "    `;",
  "",
  "    const program = gl.createProgram();",
  "    for (const [type, source] of [[gl.VERTEX_SHADER, vertex], [gl.FRAGMENT_SHADER, fragment]]) {",
  "      const shader = gl.createShader(type);",
  "      gl.shaderSource(shader, source);",
  "      gl.compileShader(shader);",
  "      console.log(gl.getShaderInfoLog(shader)); // shader errors show up here",
  "      gl.attachShader(program, shader);",
  "    }",
  "    gl.linkProgram(program);",
  "    gl.useProgram(program);",
  "",
  "    // One triangle big enough to cover the whole screen.",
  "    gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer());",
  "    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);",
  "    gl.enableVertexAttribArray(0);",
  "    gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 0, 0);",
  "",
  "    const time = gl.getUniformLocation(program, \"t\");",
  "    const size = gl.getUniformLocation(program, \"r\");",
  "",
  "    onresize = () => {",
  "      c.width = innerWidth;",
  "      c.height = innerHeight;",
  "      gl.viewport(0, 0, c.width, c.height);",
  "      gl.uniform2f(size, c.width, c.height);",
  "    };",
  "    onresize();",
  "",
  "    function frame(ms) {",
  "      gl.uniform1f(time, ms / 1000);",
  "      gl.drawArrays(gl.TRIANGLES, 0, 3);",
  "      requestAnimationFrame(frame);",
  "    }",
  "    requestAnimationFrame(frame);",
  "  </script>",
  "</body>",
].join("\n");

export const SOUND_BEEP = [
  "let audio;",
  "",
  "// Make the audio context on the first click or key press.",
  "// addEventListener is used here so it doesn't replace your own onpointerdown or onkeydown.",
  "const unlock = () => (audio ??= new AudioContext());",
  "addEventListener(\"pointerdown\", unlock);",
  "addEventListener(\"keydown\", unlock);",
  "",
  "function beep(freq, length = 0.2, type = \"square\", when) {",
  "  if (!audio) return; // no click yet, so no sound",
  "  when ??= audio.currentTime;",
  "  const osc = audio.createOscillator();",
  "  const gain = audio.createGain();",
  "  osc.type = type;",
  "  osc.frequency.value = freq;",
  "  // Start at 0.2 and fade out. It fades to 0.001 instead of 0",
  "  // because this kind of fade can't reach zero.",
  "  gain.gain.setValueAtTime(0.2, when);",
  "  gain.gain.exponentialRampToValueAtTime(0.001, when + length);",
  "  osc.connect(gain).connect(audio.destination);",
  "  osc.start(when);",
  "  osc.stop(when + length);",
  "}",
].join("\n");

export const SOUND_JUMP = [
  "function jump() {",
  "  if (!audio) return;",
  "  const t = audio.currentTime;",
  "  const osc = audio.createOscillator();",
  "  const gain = audio.createGain();",
  "  osc.type = \"square\";",
  "  osc.frequency.setValueAtTime(200, t);",
  "  osc.frequency.exponentialRampToValueAtTime(800, t + 0.15); // slide up",
  "  gain.gain.setValueAtTime(0.2, t);",
  "  gain.gain.exponentialRampToValueAtTime(0.001, t + 0.15);",
  "  osc.connect(gain).connect(audio.destination);",
  "  osc.start(t);",
  "  osc.stop(t + 0.15);",
  "}",
].join("\n");

export const SOUND_NOTES = [
  "// note number to frequency. 60 is middle C, and each +1 is one piano key higher",
  "const note = (n) => 440 * 2 ** ((n - 69) / 12);",
  "",
  "// these five sound fine together in any order",
  "const scale = [0, 2, 4, 7, 9];",
  "",
  "// a random note from the scale, starting at middle C or the C above it",
  "const randomNote = () => note(60 + scale[(Math.random() * 5) | 0] + 12 * ((Math.random() * 2) | 0));",
].join("\n");

export const SOUND_ARPEGGIO = [
  "// call this from a click or key handler, after the audio has started",
  "function arpeggio() {",
  "  if (!audio) return;",
  "  const now = audio.currentTime;",
  "  beep(note(60), 0.2, \"square\", now);",
  "  beep(note(64), 0.2, \"square\", now + 0.2);",
  "  beep(note(67), 0.2, \"square\", now + 0.4);",
  "}",
].join("\n");

export const SOUND_NOISE = [
  "function noise(length, cutoff, when) {",
  "  if (!audio) return;",
  "  when ??= audio.currentTime;",
  "  // a buffer full of random numbers is static",
  "  const buffer = audio.createBuffer(1, audio.sampleRate * length, audio.sampleRate);",
  "  const data = buffer.getChannelData(0);",
  "  for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;",
  "",
  "  const source = audio.createBufferSource();",
  "  const filter = audio.createBiquadFilter();",
  "  const gain = audio.createGain();",
  "  source.buffer = buffer;",
  "  filter.type = \"highpass\"; // only lets the high sounds through",
  "  filter.frequency.value = cutoff; // about 7000 for a hi-hat, 1000 for a snare",
  "  gain.gain.setValueAtTime(0.3, when);",
  "  gain.gain.exponentialRampToValueAtTime(0.001, when + length);",
  "  source.connect(filter).connect(gain).connect(audio.destination);",
  "  source.start(when);",
  "}",
  "",
  "// a kick is a low tone that drops fast",
  "function kick(when) {",
  "  if (!audio) return;",
  "  when ??= audio.currentTime;",
  "  const osc = audio.createOscillator();",
  "  const gain = audio.createGain();",
  "  osc.frequency.setValueAtTime(150, when);",
  "  osc.frequency.exponentialRampToValueAtTime(40, when + 0.3);",
  "  gain.gain.setValueAtTime(0.8, when);",
  "  gain.gain.exponentialRampToValueAtTime(0.001, when + 0.3);",
  "  osc.connect(gain).connect(audio.destination);",
  "  osc.start(when);",
  "  osc.stop(when + 0.3);",
  "}",
].join("\n");

export const SOUND_LOOP = [
  "const kicks = \"x...x...x...x...\";",
  "const hats = \"..x...x...x...xx\"; // both patterns need the same length",
  "const stepLength = 60 / 120 / 4; // 120 beats per minute, 4 steps per beat",
  "let step = 0;",
  "let nextTime = 0;",
  "",
  "setInterval(() => {",
  "  if (!audio) return;",
  "  if (nextTime < audio.currentTime) nextTime = audio.currentTime;",
  "  // schedule every step that's due in the next 0.1 seconds",
  "  while (nextTime < audio.currentTime + 0.1) {",
  "    if (kicks[step] == \"x\") kick(nextTime);",
  "    if (hats[step] == \"x\") noise(0.05, 7000, nextTime);",
  "    step = (step + 1) % kicks.length;",
  "    nextTime += stepLength;",
  "  }",
  "}, 25);",
].join("\n");

export const INPUT_KEYS = [
  "const held = {};",
  "onkeydown = (e) => {",
  "  held[e.code] = true;",
  "  // stop arrows and space from scrolling the page",
  "  if (e.code.startsWith(\"Arrow\") || e.code == \"Space\") e.preventDefault();",
  "};",
  "onkeyup = (e) => (held[e.code] = false);",
].join("\n");

export const INPUT_UPDATE = [
  "function update(dt) {",
  "  if (held.ArrowLeft || held.KeyA) player.x -= 200 * dt;",
  "  if (held.ArrowRight || held.KeyD) player.x += 200 * dt;",
  "}",
].join("\n");

export const INPUT_POINTER = [
  "let pointer = { x: 0, y: 0, down: false };",
  "",
  "onpointermove = (e) => {",
  "  // turn the position on screen into a position on the canvas,",
  "  // even if the canvas is moved or stretched with CSS",
  "  const box = c.getBoundingClientRect();",
  "  pointer.x = ((e.clientX - box.left) * c.width) / box.width;",
  "  pointer.y = ((e.clientY - box.top) * c.height) / box.height;",
  "};",
  "onpointerdown = (e) => {",
  "  pointer.down = true;",
  "  onpointermove(e);",
  "};",
  "onpointerup = () => (pointer.down = false);",
].join("\n");

export const CANVAS_TRAILS = [
  "function draw(time) {",
  "  // a see-through rectangle instead of a clear leaves trails",
  "  ctx.fillStyle = \"rgba(0, 0, 0, 0.15)\";",
  "  ctx.fillRect(0, 0, c.width, c.height);",
  "",
  "  for (let i = 0; i < 12; i++) {",
  "    const angle = time / 1000 + i / 2;",
  "    ctx.fillStyle = `hsl(${i * 30} 90% 60%)`;",
  "    ctx.beginPath();",
  "    ctx.arc(c.width / 2 + Math.cos(angle) * 150, c.height / 2 + Math.sin(angle * 1.3) * 150, 10, 0, 7);",
  "    ctx.fill();",
  "  }",
  "}",
].join("\n");

export const CANVAS_ROTATE = [
  "ctx.save();",
  "ctx.translate(200, 150); // move to where the middle of the square should be",
  "ctx.rotate(time / 500); // spin a bit more every frame",
  "ctx.fillRect(-25, -25, 50, 50); // draw it centered on that point",
  "ctx.restore(); // undo the move and the spin",
].join("\n");

export const CANVAS_PIXELS = [
  "<canvas id=\"c\" width=\"160\" height=\"90\"></canvas>",
  "<style>",
  "  body { margin: 0; overflow: hidden; }",
  "  canvas { width: 100vw; height: 100vh; image-rendering: pixelated; }",
  "</style>",
  "<script>",
  "  const ctx = c.getContext(\"2d\");",
  "  const img = ctx.createImageData(160, 90);",
  "",
  "  function frame(time) {",
  "    for (let y = 0; y < 90; y++) {",
  "      for (let x = 0; x < 160; x++) {",
  "        const v = Math.sin(x / 8 + time / 900) + Math.sin(y / 6 - time / 700);",
  "        const i = (y * 160 + x) * 4; // where this pixel's 4 numbers start",
  "        img.data[i] = 128 + 127 * Math.sin(v * 3); // red",
  "        img.data[i + 1] = 128 + 127 * Math.sin(v * 3 + 2); // green",
  "        img.data[i + 2] = 200; // blue",
  "        img.data[i + 3] = 255; // opacity",
  "      }",
  "    }",
  "    ctx.putImageData(img, 0, 0);",
  "    requestAnimationFrame(frame);",
  "  }",
  "  requestAnimationFrame(frame);",
  "</script>",
].join("\n");

export const THREE_PROJECTION = [
  "const { sin, cos, random } = Math;",
  "",
  "// 500 random points in a cube that goes from -1 to 1",
  "const points = Array.from({ length: 500 }, () => [random() * 2 - 1, random() * 2 - 1, random() * 2 - 1]);",
  "",
  "function project([x, y, z], angle) {",
  "  // spin around the up-down axis",
  "  const rx = x * cos(angle) - z * sin(angle);",
  "  let rz = x * sin(angle) + z * cos(angle);",
  "  let ry = y;",
  "  rz += 3; // push it away from the camera so it's in front of us",
  "  const scale = c.height / rz; // further away = smaller",
  "  return [c.width / 2 + rx * scale, c.height / 2 + ry * scale, rz];",
  "}",
  "",
  "function draw(time) {",
  "  ctx.fillStyle = \"black\";",
  "  ctx.fillRect(0, 0, c.width, c.height);",
  "  const projected = points.map((p) => project(p, time / 2000));",
  "  projected.sort((a, b) => b[2] - a[2]); // far ones first, so near ones end up on top",
  "  for (const [x, y, z] of projected) {",
  "    const size = 12 / z;",
  "    ctx.fillStyle = `hsl(40 100% ${90 - z * 15}%)`;",
  "    ctx.fillRect(x - size / 2, y - size / 2, size, size);",
  "  }",
  "}",
].join("\n");
